services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  discountdb:
    container_name: discountdb
    restart: always
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=Password@1"
      - "POSTGRES_DB=DiscountDb"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 10s
      timeout: 5s
      retries: 5

  orderdb:
    container_name: orderdb
    restart: always
    environment:
      SA_PASSWORD: "Pa55w0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - orderdb_data:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/optmssql-tools/bin/sqlcmd -S localhost -U sa -P 'Pa55w0rd' -Q 'select 1" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s

  catalog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings__DatabaseName=CatalogDb"
      - "DatabaseSettings__ProductCollectionName=Products"
      - "DatabaseSettings__BrandCollectionName=Brands"
      - "DatabaseSettings__TypeCollectionName=Types"
    depends_on:
      - catalogdb
    ports:
      - "8000:8080"

  basket:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings__ConnectionString=basketdb:6379"
      - "GrpcSettings__DiscountUrl=http://discount:8080"
      - "EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "ElasticConfiguration__Uri=http://elasticsearch:9200"
    depends_on:
      - basketdb
    ports:
      - "8001:8080"

  discount:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__Default=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=Password@1;"
      - "ElasticConfiguration__Uri=http://elasticsearch:9200"
    ports:
      - "8002:8080"
    depends_on:
      - discountdb

  ordering:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__OrderingConnectionString=Server=orderdb,1433;Database=OrderDb;User id=sa;Password=Pa55w0rd;TrustServerCertificate=True;"
    ports:
      - "8003:8080"
    depends_on:
      - orderdb