services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  catalog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings__DatabaseName=CatalogDb"
      - "DatabaseSettings__ProductCollectionName=Products"
      - "DatabaseSettings__BrandCollectionName=Brands"
      - "DatabaseSettings__TypeCollectionName=Types"
    depends_on:
      - catalogdb
    ports:
      - "8000:8080"

  basket:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings__ConnectionString=basketdb:6379"
      - "GrpcSettings__DiscountUrl=http://discount:8080"
      - "EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "ElasticConfiguration__Uri=http://elasticsearch:9200"
    depends_on:
      - basketdb
    ports:
      - "8001:8080"
