<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Basket.Core/Basket.Core.csproj" />
    <ProjectReference Include="../../../Infrastructure/EventBus.Messages/EventBus.Messages.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos/discount.proto" GrpcServices="Client" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="9.2.1" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="9.2.1" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.83.0" />
    <PackageReference Include="Grpc.Net.Client" Version="2.83.0" />
    <PackageReference Include="Grpc.Tools" Version="2.83.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

</Project>